### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by clin045** [singularityhub/singularity-cli#160] opened 2020-05-14 18:11 UTC
## Expected Behavior

`spython recipe Dockerfile` should convert my Dockerfile to a singularity recipe

## Actual Behavior

I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/spython", line 11, in <module>
    load_entry_point('spython==0.0.80', 'console_scripts', 'spython')()
  File "/usr/local/lib/python3.6/site-packages/spython-0.0.80-py3.6.egg/spython/client/__init__.py", line 198, in main
    func(args=args, options=options, parser=parser)
  File "/usr/local/lib/python3.6/site-packages/spython-0.0.80-py3.6.egg/spython/client/recipe.py", line 63, in main
    recipeParser = parser(args.files[0])
  File "/usr/local/lib/python3.6/site-packages/spython-0.0.80-py3.6.egg/spython/main/parse/parsers/docker.py", line 30, in __init__
    super(DockerParser, self).__init__(filename, load)
  File "/usr/local/lib/python3.6/site-packages/spython-0.0.80-py3.6.egg/spython/main/parse/parsers/base.py", line 47, in __init__
    self.parse()
  File "/usr/local/lib/python3.6/site-packages/spython-0.0.80-py3.6.egg/spython/main/parse/parsers/docker.py", line 56, in parse
    parser(line)
  File "/usr/local/lib/python3.6/site-packages/spython-0.0.80-py3.6.egg/spython/main/parse/parsers/docker.py", line 152, in _env
    environ = self.parse_env(line)
  File "/usr/local/lib/python3.6/site-packages/spython-0.0.80-py3.6.egg/spython/main/parse/parsers/docker.py", line 200, in parse_env
    nextone = pieces.pop(0)
IndexError: pop from empty list
```

## Context
* Operating System: Reproduced on both CentOS 7.8 and MacOS 10.15
* singularity version: 2.5.2 
* spython version: 0.0.80, both from pypi and github
* python version: 3.6.8

**Comment by vsoch** [comment] 2020-05-14 18:43
Could you please share the Dockerfile so I can reproduce? Thank you!

**Comment by clin045** [comment] 2020-05-15 17:39
https://gist.github.com/clin045/d49f102b24d0e8911a92a6912791d8bc

**Comment by vsoch** [comment] 2020-05-15 17:46
Thanks for the recipe! It looks like you have a typo in your file -

```          
FSLDIR /usr/share/fsl/5.0 /
```
The slash has a space after the 5.0 that should not be there.

**Comment by vsoch** [comment] 2020-05-15 17:48
And note that it appears twice in the file.

**Comment by clin045** [comment] 2020-05-15 17:50
Ah I see. Thank you for the help!

**Comment by vsoch** [comment] 2020-05-15 18:07
Of course! Sometimes you just need another eye, and that I can definitely offer... actually I have two :)

Closing issue, please re-open if needed.

**Closed by vsoch** 2020-05-15 18:07 UTC
