### ISSUE TITLE
chained commands

### ISSUE THREAD

**Issue by samcmill** [singularityhub/singularity-cli#23] opened 2018-04-19 15:44 UTC
It is common in Docker to chain commands together into a single layer and break the command so it does not exceed 80 characters. For instance:

```
RUN apt-get update -y && \
  apt-get-install -y --no-install-recommends \
     python \
     python3 && \
  rm -rf /var/lib/apt/lists/* 
```

This is converted to Singularity as

```
%post
apt-get update -y && \
apt-get install -y --no-install-recommends \
python \
python3 && \
rm -rf /var/lig/apt/lists/*
```

The builder then interprets this as 5 effective commands rather than 1 long command split over 5 lines. The builder fails when trying to run `python`.

**Comment by vsoch** [comment] 2018-04-19 18:47
Could you provide the entire recipe file here, and what is the issue? This I think is the correct parsing that we would want. For example, here is a Singularity recipe:

```
Bootstrap: docker
From: ubuntu

%post
apt-get update -y && \
apt-get install -y --no-install-recommends \
python \
python3 && \
rm -rf /var/lig/apt/lists/*
```
And the build works as expected.

```
$ sudo singularity build test.simg Singularity 
[sudo] password for vanessa: 
Using container recipe deffile: Singularity
Sanitizing environment
Adding base Singularity environment to container
Docker image path: index.docker.io/library/ubuntu:latest
Cache folder set to /root/.singularity/docker
[5/5] |===================================| 100.0% 
Exploding layer: sha256:d3938036b19cfa369e1081a6776b07b54be9612bc4c8fed7f139370c8142b79f.tar.gz
Exploding layer: sha256:a9b30c108bda615dc10e402f62d712f413214ea92c7ec4354cd1cc0f3450bc58.tar.gz
Exploding layer: sha256:67de21feec183fcd009a5eddc4de8c346ee0f4369a20047f1a302a90716fc741.tar.gz
Exploding layer: sha256:817da545be2ba4bac8f6b4da584bca0fb4844938ecc462b9feab1001b5df7405.tar.gz
Exploding layer: sha256:d967c497ce230b63996a7b1fc6ec95b741aea9348118d3328c676f13be789fa7.tar.gz
Exploding layer: sha256:c6a9ef4b9995d615851d7786fbc2fe72f72321bee1a87d66919b881a0336525a.tar.gz
Running post scriptlet
+ apt-get update -y
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]                                        
Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]                           
Get:5 http://archive.ubuntu.com/ubuntu xenial/universe Sources [9802 kB]                             
Get:6 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [79.0 kB]
Get:7 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [602 kB]                         
Get:8 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [431 kB]                        
Get:9 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [3489 B]                      
Get:10 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9827 kB]                                
Get:11 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [176 kB]                               
Get:12 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [253 kB]                                
Get:13 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [979 kB]                             
Get:14 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [800 kB]                         
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [18.5 kB]                      
Get:16 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [5153 B]                           
Get:17 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [7734 B]                       
Fetched 23.3 MB in 21s (1070 kB/s)                                                                              
Reading package lists... Done
+ apt-get install -y --no-install-recommends python python3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  dh-python libexpat1 libffi6 libmpdec2 libpython-stdlib libpython2.7-minimal libpython2.7-stdlib
  libpython3-stdlib libpython3.5-minimal libpython3.5-stdlib libsqlite3-0 libssl1.0.0 mime-support
  python-minimal python2.7 python2.7-minimal python3-minimal python3.5 python3.5-minimal
Suggested packages:
  libdpkg-perl python-doc python-tk python2.7-doc binutils binfmt-support python3-doc python3-tk python3-venv
  python3.5-venv python3.5-doc
Recommended packages:
  file
The following NEW packages will be installed:
  dh-python libexpat1 libffi6 libmpdec2 libpython-stdlib libpython2.7-minimal libpython2.7-stdlib
  libpython3-stdlib libpython3.5-minimal libpython3.5-stdlib libsqlite3-0 libssl1.0.0 mime-support python
  python-minimal python2.7 python2.7-minimal python3 python3-minimal python3.5 python3.5-minimal
0 upgraded, 21 newly installed, 0 to remove and 5 not upgraded.
Need to get 10.1 MB of archives.
After this operation, 45.7 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libssl1.0.0 amd64 1.0.2g-1ubuntu4.12 [1085 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpython3.5-minimal amd64 3.5.2-2ubuntu0~16.04.4 [523 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libexpat1 amd64 2.1.0-7ubuntu0.16.04.3 [71.2 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 python3.5-minimal amd64 3.5.2-2ubuntu0~16.04.4 [1597 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial/main amd64 python3-minimal amd64 3.5.1-3 [23.3 kB]
Get:6 http://archive.ubuntu.com/ubuntu xenial/main amd64 mime-support all 3.59ubuntu1 [31.0 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial/main amd64 libmpdec2 amd64 2.4.2-1 [82.6 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial/main amd64 libsqlite3-0 amd64 3.11.0-1ubuntu1 [396 kB]
Get:9 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpython3.5-stdlib amd64 3.5.2-2ubuntu0~16.04.4 [2132 kB]
Get:10 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 python3.5 amd64 3.5.2-2ubuntu0~16.04.4 [165 kB]
Get:11 http://archive.ubuntu.com/ubuntu xenial/main amd64 libpython3-stdlib amd64 3.5.1-3 [6818 B]
Get:12 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 dh-python all 2.20151103ubuntu1.1 [74.1 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial/main amd64 python3 amd64 3.5.1-3 [8710 B]
Get:14 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpython2.7-minimal amd64 2.7.12-1ubuntu0~16.04.3 [340 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 python2.7-minimal amd64 2.7.12-1ubuntu0~16.04.3 [1261 kB]
Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 python-minimal amd64 2.7.12-1~16.04 [28.1 kB] 
Get:17 http://archive.ubuntu.com/ubuntu xenial/main amd64 libffi6 amd64 3.2.1-4 [17.8 kB]                       
Get:18 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpython2.7-stdlib amd64 2.7.12-1ubuntu0~16.04.3 [1880 kB]
Get:19 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 python2.7 amd64 2.7.12-1ubuntu0~16.04.3 [224 kB]
Get:20 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpython-stdlib amd64 2.7.12-1~16.04 [7768 B]
Get:21 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 python amd64 2.7.12-1~16.04 [137 kB]          
Fetched 10.1 MB in 9s (1053 kB/s)                                                                               
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libssl1.0.0:amd64.
(Reading database ... 4768 files and directories currently installed.)
Preparing to unpack .../libssl1.0.0_1.0.2g-1ubuntu4.12_amd64.deb ...
Unpacking libssl1.0.0:amd64 (1.0.2g-1ubuntu4.12) ...
Selecting previously unselected package libpython3.5-minimal:amd64.
Preparing to unpack .../libpython3.5-minimal_3.5.2-2ubuntu0~16.04.4_amd64.deb ...
Unpacking libpython3.5-minimal:amd64 (3.5.2-2ubuntu0~16.04.4) ...
Selecting previously unselected package libexpat1:amd64.
Preparing to unpack .../libexpat1_2.1.0-7ubuntu0.16.04.3_amd64.deb ...
Unpacking libexpat1:amd64 (2.1.0-7ubuntu0.16.04.3) ...
Selecting previously unselected package python3.5-minimal.
Preparing to unpack .../python3.5-minimal_3.5.2-2ubuntu0~16.04.4_amd64.deb ...
Unpacking python3.5-minimal (3.5.2-2ubuntu0~16.04.4) ...
Selecting previously unselected package python3-minimal.
Preparing to unpack .../python3-minimal_3.5.1-3_amd64.deb ...
Unpacking python3-minimal (3.5.1-3) ...
Selecting previously unselected package mime-support.
Preparing to unpack .../mime-support_3.59ubuntu1_all.deb ...
Unpacking mime-support (3.59ubuntu1) ...
Selecting previously unselected package libmpdec2:amd64.
Preparing to unpack .../libmpdec2_2.4.2-1_amd64.deb ...
Unpacking libmpdec2:amd64 (2.4.2-1) ...
Selecting previously unselected package libsqlite3-0:amd64.
Preparing to unpack .../libsqlite3-0_3.11.0-1ubuntu1_amd64.deb ...
Unpacking libsqlite3-0:amd64 (3.11.0-1ubuntu1) ...
Selecting previously unselected package libpython3.5-stdlib:amd64.
Preparing to unpack .../libpython3.5-stdlib_3.5.2-2ubuntu0~16.04.4_amd64.deb ...
Unpacking libpython3.5-stdlib:amd64 (3.5.2-2ubuntu0~16.04.4) ...
Selecting previously unselected package python3.5.
Preparing to unpack .../python3.5_3.5.2-2ubuntu0~16.04.4_amd64.deb ...
Unpacking python3.5 (3.5.2-2ubuntu0~16.04.4) ...
Selecting previously unselected package libpython3-stdlib:amd64.
Preparing to unpack .../libpython3-stdlib_3.5.1-3_amd64.deb ...
Unpacking libpython3-stdlib:amd64 (3.5.1-3) ...
Selecting previously unselected package dh-python.
Preparing to unpack .../dh-python_2.20151103ubuntu1.1_all.deb ...
Unpacking dh-python (2.20151103ubuntu1.1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Setting up libssl1.0.0:amd64 (1.0.2g-1ubuntu4.12) ...
Setting up libpython3.5-minimal:amd64 (3.5.2-2ubuntu0~16.04.4) ...
Setting up libexpat1:amd64 (2.1.0-7ubuntu0.16.04.3) ...
Setting up python3.5-minimal (3.5.2-2ubuntu0~16.04.4) ...
Setting up python3-minimal (3.5.1-3) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Selecting previously unselected package python3.
(Reading database ... 5744 files and directories currently installed.)
Preparing to unpack .../python3_3.5.1-3_amd64.deb ...
Unpacking python3 (3.5.1-3) ...
Selecting previously unselected package libpython2.7-minimal:amd64.
Preparing to unpack .../libpython2.7-minimal_2.7.12-1ubuntu0~16.04.3_amd64.deb ...
Unpacking libpython2.7-minimal:amd64 (2.7.12-1ubuntu0~16.04.3) ...
Selecting previously unselected package python2.7-minimal.
Preparing to unpack .../python2.7-minimal_2.7.12-1ubuntu0~16.04.3_amd64.deb ...
Unpacking python2.7-minimal (2.7.12-1ubuntu0~16.04.3) ...
Selecting previously unselected package python-minimal.
Preparing to unpack .../python-minimal_2.7.12-1~16.04_amd64.deb ...
Unpacking python-minimal (2.7.12-1~16.04) ...
Selecting previously unselected package libffi6:amd64.
Preparing to unpack .../libffi6_3.2.1-4_amd64.deb ...
Unpacking libffi6:amd64 (3.2.1-4) ...
Selecting previously unselected package libpython2.7-stdlib:amd64.
Preparing to unpack .../libpython2.7-stdlib_2.7.12-1ubuntu0~16.04.3_amd64.deb ...
Unpacking libpython2.7-stdlib:amd64 (2.7.12-1ubuntu0~16.04.3) ...
Selecting previously unselected package python2.7.
Preparing to unpack .../python2.7_2.7.12-1ubuntu0~16.04.3_amd64.deb ...
Unpacking python2.7 (2.7.12-1ubuntu0~16.04.3) ...
Selecting previously unselected package libpython-stdlib:amd64.
Preparing to unpack .../libpython-stdlib_2.7.12-1~16.04_amd64.deb ...
Unpacking libpython-stdlib:amd64 (2.7.12-1~16.04) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Setting up libpython2.7-minimal:amd64 (2.7.12-1ubuntu0~16.04.3) ...
Setting up python2.7-minimal (2.7.12-1ubuntu0~16.04.3) ...
Setting up python-minimal (2.7.12-1~16.04) ...
Selecting previously unselected package python.
(Reading database ... 6513 files and directories currently installed.)
Preparing to unpack .../python_2.7.12-1~16.04_amd64.deb ...
Unpacking python (2.7.12-1~16.04) ...
Setting up mime-support (3.59ubuntu1) ...
Setting up libmpdec2:amd64 (2.4.2-1) ...
Setting up libsqlite3-0:amd64 (3.11.0-1ubuntu1) ...
Setting up libpython3.5-stdlib:amd64 (3.5.2-2ubuntu0~16.04.4) ...
Setting up python3.5 (3.5.2-2ubuntu0~16.04.4) ...
Setting up libpython3-stdlib:amd64 (3.5.1-3) ...
Setting up libffi6:amd64 (3.2.1-4) ...
Setting up libpython2.7-stdlib:amd64 (2.7.12-1ubuntu0~16.04.3) ...
Setting up python2.7 (2.7.12-1ubuntu0~16.04.3) ...
Setting up libpython-stdlib:amd64 (2.7.12-1~16.04) ...
Setting up python (2.7.12-1~16.04) ...
Setting up python3 (3.5.1-3) ...
Setting up dh-python (2.20151103ubuntu1.1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
+ rm -rf /var/lig/apt/lists/*
Finalizing Singularity container
Calculating final size for metadata...
Skipping checks
Building Singularity image...
Singularity container built: test.simg
Cleaning up...
```
The builder isn't actually running python anywhere, so I need a little more detail, thanks!

**Comment by samcmill** [comment] 2018-04-20 13:59
I tried the build from the Tunel interface, not using `singularity build`.  The corresponding log is:

```
==> /tmp/gunicorn-access.log <==
127.0.0.1 - - [19/Apr/2018:14:11:46 +0000] "POST /recipe HTTP/1.0" 200 18977 "http://127.0.0.1/recipe" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
+ apt-get update -y
+ apt-get install -y --no-install-recommends
+ python
/bin/sh: 8: python: not found
ABORT: Aborting with RETVAL=255
127.0.0.1 - - [19/Apr/2018:14:12:44 +0000] "POST /action/add HTTP/1.0" 200 59 "http://127.0.0.1/recipe" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
```

**Comment by vsoch** [comment] 2018-04-20 14:12
yeah! There is a bug currently with Globus, I have the fix ready to go but I was waiting on this PR, haha.

**Comment by vsoch** [comment] 2018-04-20 14:12
I'm not sure why it's trying to call python from within the build, but this is perfect giving me something to test with for this issue.

**Comment by vsoch** [comment] 2018-04-20 15:06
okay, testing now! Here is the original Dockerfile:

```
FROM ubuntu

RUN apt-get update -y && \
  apt-get-install -y --no-install-recommends \
     python \
     python3 && \
  rm -rf /var/lib/apt/lists/* 
```
and this is converted to this in the interface:

```
Bootstrap: docker
From: ubuntu
%post
apt-get update -y && \
apt-get-install -y --no-install-recommends \
python \
python3 && \
rm -rf /var/lib/apt/lists/*
%runscript
exec /bin/bash "$@"
```
I reproduced your error:

```
==> /tmp/gunicorn.log <==
[2018-04-20 14:58:23 +0000] [55] [ERROR] Error handling request
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    for item in respiter:
  File "/opt/conda/lib/python3.6/site-packages/werkzeug/wsgi.py", line 693, in __next__
    return self._next()
  File "/opt/conda/lib/python3.6/site-packages/werkzeug/wrappers.py", line 81, in _iter_encoded
    for item in iterable:
  File "/opt/conda/lib/python3.6/site-packages/spython-0.0.29-py3.6.egg/spython/utils/terminal.py", line 95, in stream_command
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command '['singularity', 'build', 'crusty-lamp-6467.simg', '/tmp/Singularity.vjjihvmv']' returned non-zero exit status 255.

==> /tmp/gunicorn-access.log <==
127.0.0.1 - - [20/Apr/2018:14:58:41 +0000] "POST /logs HTTP/1.0" 200 3455 "http://127.0.0.1/recipe" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
```
First testing the build (from singularity native) and I'm hitting a different bug first:

```
+ apt-get-install -y --no-install-recommends
/bin/sh: 4: apt-get-install: not found
ABORT: Aborting with RETVAL=255
Cleaning up...
```
Were you using the Dockerfile above that has `apt-get-install` or a fixed version? With that fix, I triggered th error, and tried removing the extra newlines in the Singularity recipe, and that did the trick on the command line! I'll update the spython tool and then retest from the interface and report back.

**Comment by samcmill** [comment] 2018-04-20 15:09
apt-get-install (with the extra dash) is likely a typo / copy-paste error on my part when I entered the issue.

**Comment by vsoch** [comment] 2018-04-20 15:55
okay no worries! Here is an update, the recipe looks ok after being parsed:

```
['Bootstrap: docker',
 'From: ubuntu',
 '%post',
 '',
 'apt-get update -y && \\',
 'apt-get-install -y --no-install-recommends \\',
 'python \\',
 'python3 && \\',
 'rm -rf /var/lib/apt/lists/*',
 '%runscript',
 'exec /bin/bash "$@"']

```
And then the finished recipe (if using spython in the terminal) also looks ok:

```
print('\n'.join(recipe).replace('\n\n','\n'))
Bootstrap: docker
From: ubuntu
%post
apt-get update -y && \
apt-get-install -y --no-install-recommends \
python \
python3 && \
rm -rf /var/lib/apt/lists/*
%runscript
exec /bin/bash "$@"
```
but the difference is that we are returning back to the web interface, and then the user is clicking build. I suspect those extra newlines are from the `\r` newlines that are added from the browser. It looks like I had anticipated the newlines, and added a replace:

```
        recipe = request.form.get('recipe').replace('\r','\n')
```
but I replaced with the wrong character! We would want to replace with the empty string. I changed that to:

```
        recipe = request.form.get('recipe').replace('\r','')
```
and that seemed to do the trick! There are a couple other bugs in the build interface I'm fixing up, I'll do that and let you know when a fresh image is ready.

**Comment by vsoch** [comment] 2018-04-20 17:26
okay PR is merged, I tested the new container, we are good I think!

![image](https://user-images.githubusercontent.com/814322/39064902-19ea9ec2-449e-11e8-9d8e-194ef069cace.png)

![image](https://user-images.githubusercontent.com/814322/39064921-274bfc64-449e-11e8-9eec-5b6251095620.png)

You were also correct about the original python bug - there were actually *two* that were very similar and related to python! Since we have python in /opt/conda/bin and singularity clears the path and looks for python in /usr/bin, the singularity software itself wasn't finding python. So the fix was to make a symbolic link:

```
ln -s /opt/conda/bin/python /usr/bin/python
```
I'm going to close the issue here, but please reopen if you have further issue.

**Closed by vsoch** 2018-04-20 17:26 UTC
