### ISSUE TITLE
Split Docker command chains to individual commands

### ISSUE THREAD

**Issue by Flamefire** [singularityhub/singularity-cli#103] opened 2019-05-23 13:09 UTC
**Is your feature request related to a problem? Please describe.**
DockerFiles usually contain chains like `this && that`. Putting them into singularity will result in a successful build even when `this` failed. This is usually not wanted. See also https://github.com/sylabs/singularity/issues/1597

**Describe the solution you'd like**
Replace all occurences of `&&` by `;` would solve this.   
For additional readability first replace `\s*&&\s*\\\n` by `\n` to remove trailing ` && \`

**Comment by vsoch** [comment] 2019-05-23 13:18
As noted here https://github.com/sylabs/singularity/issues/1597#issuecomment-411858773 this is expected behavior and the recipe needs to set `-e errexit`. It's out of scope for the converter to try and parse the && statements, as this is an issue with the shell.

**Comment by vsoch** [comment] 2019-05-23 13:19
If you have a solution that you think is better, I'm happy to review a PR for it.

**Comment by Flamefire** [comment] 2019-05-23 13:23
> As noted here sylabs/singularity#1597 (comment) this is expected behavior and the recipe needs to set -e errexit

Sorry but this is not correct as that very comment states:

> I'm using the same technique [...]: removing the && chains when I convert from Docker to Singularity.

So this is what others do manually when converting DockerFiles to Singularity which IMO makes it suitable for the converter. There is nothing else that can be done to have failing commands fail the build

I'll create a PR once I have time

**Comment by donkirkby** [comment] 2019-05-27 22:08
Can I suggest a smaller change to avoid this problem? If you wrap the commands in parentheses when converting from a Dockerfile `RUN` command, then any errors will fail the singularity build.

To be more explicit, here's the original recipe file from sylabs/singularity#1597:

```
BootStrap: docker
From: debian:stretch

%post
  apt-get update
  apt-get install -y --no-install-recommends \
    wget \
    blahblahblah \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*
  echo 'I will valiantly keep the build from failing!'
```

Building that reports a failure when it tries to install `blahblahblah`, but the build continues. That's because the `apt-get-install` command is followed by `&& apt-get clean`. The shell thinks that means that the `apt-get-install` command's error is being tested for and dealt with using the conditional logic.

That's a problem, because it now behaves differently from the Dockerfile it was based on. Here's the docker file I imagine it was based on:

```
FROM debian:stretch

RUN  apt-get update
RUN  apt-get install -y --no-install-recommends \
    wget \
    blahblahblah \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN  echo 'I will valiantly keep the build from failing!'
```

That docker file will fail, as expected.

Now here's a new singularity recipe where I've added parentheses around the `RUN` commands.

```
BootStrap: docker
From: debian:stretch

%post
  ( apt-get update )
  ( apt-get install -y --no-install-recommends \
    wget \
    blahblahblah \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/* )
  ( echo 'I will valiantly keep the build from failing!' )
```

That version fails in exactly the same way that the docker file does, and it doesn't require any parsing of the `RUN` commands. Just surround all of them with parentheses. If you want to be more sophisticated, you could leave off the parentheses unless you see logical operators in the command.

**Comment by vsoch** [comment] 2019-05-27 22:18
@donkirkby this is a cool idea! It definitely is non traditional (meaning you wouldn't find a Singularity recipe like that in the wild) but I just tested it, and fails as promised!

```
...
Reading state information... Done
E: Unable to locate package blahblahblah
FATAL:   post proc: exit status 100
FATAL:   While performing build: while running engine: exit status 255
```
I added some echos to see the return codes, and it looks like each line is a subshell that is called, with the return code triggering the success/fail? That's cool! Would there be any issue with running things in a subshell, generally?

Here are the echos:

```
BootStrap: docker
From: debian:stretch

%post
  ( apt-get update )
  echo $?
  ( apt-get install -y --no-install-recommends \
    wget \
    blahblahblah \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/* )
  echo $?
  ( echo 'I will valiantly keep the build from failing!' )
```
and here we see the values 0 and we never make it to echo the failure

```bash
...
Reading package lists... Done
+ echo 0
0
+ apt-get install -y --no-install-recommends wget blahblahblah
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package blahblahblah
FATAL:   post proc: exit status 100
FATAL:   While performing build: while running engine: exit status 255
```

@Flamefire what are your thoughts? This seems like a cool approach.

**Comment by donkirkby** [comment] 2019-05-27 22:34
I agree that you wouldn't do this when you're writing a regular recipe file, @vsoch. I'm only suggesting it as a way to automatically convert docker file `RUN` commands. That's also the reason I suggested leaving off the parentheses unless you see logical operators in the command.

**Comment by vsoch** [comment] 2019-05-27 22:35
Understood @donkirkby, it's a good idea! I want to get @Flamefire thoughts as well.

**Comment by Flamefire** [comment] 2019-05-28 06:32
Looks good. The parsing approach would have the advantage of "looking more natural" but may lead to broken def files (but at least they throw an error instead of ignoring one as of current state)

For completeness: I'd parse every (mutli-line) `RUN` section and add a new level for each `"'({` char unless it is escaped or remove a level if the last level was opened by the same char. On encountering a `&&` I'd split the line there if you are currently on the top-level. I'm pretty sure this should cover all cases and "look good".

@donkirkby approach is easier to implement

In any case we need test cases for the conversion. How would you like them?
1. Have a `testFiles` folder containing pairs of DockerFile and `Singularity.def` files and test that converting docker->singularity returns the def file
2. Specify the file contents inline in the python tests (might be long) but more readable (except for long)

In both cases I'd strip leading and trailing whitespace from each line before comparison for some robustness. But could leave them as is (especially for the files approach) so one can test that the files "look good"

Just make a call

**Comment by vsoch** [comment] 2019-05-28 16:57
The directory of files would be easiest for the developer to look over - if we wrote in a general format where the files could be globbed, and then looked for an expected second file. For example:

```
testFiles/
  Dockerfile.example1
  Singularity.example1
```

We would glob for Dockerfile*, find `Dockerfile.example1` and then expect the converted file to be `Singularity.example1`. This way, whenever we need to add another kind of file for testing, we can just dump those two in that folder and it will be detected.

**Comment by Flamefire** [comment] 2019-05-28 17:39
Yes that is what I meant.
Downside is that you don't have input and expected output side by side. But others (clang-format) do the same (files) 
But I would switch things around: foo.def & foo.docker. So you have the files next to each other

**Comment by vsoch** [comment] 2019-05-28 17:41
Yep that works :)

**Closed** 2020-04-28 23:11 UTC
Labels: wontfix
