### ISSUE TITLE
Handle ENTRYPOINT+CMD in Docker2Singularity

### ISSUE THREAD

**Issue by Flamefire** [singularityhub/singularity-cli#111] opened 2019-05-28 07:15 UTC
**Is your feature request related to a problem? Please describe.**
A DockerFile can have both `ENTRYPOINT` and `CMD`. According to [this](https://www.freecodecamp.org/news/docker-entrypoint-cmd-dockerfile-best-practices-abc591c30e21/) or [that](https://docs.docker.com/engine/reference/builder/#cmd) I assume the meaning would be something like "if arguments are given to `container run` then use those, else use `CMD`" (Correct me if I'm wrong, I'm no Docker expert)

**Describe the solution you'd like**
Append `CMD` to `ENTRYPOINT` at container runtime if no arguments given

**Describe alternatives you've considered**
Use `ENTRYPOINT` or `CMD` in `%runscript` and create a `%startscript` with both if both are given as the combination is usually used for services (see above link)

**Comment by vsoch** [comment] 2019-05-28 16:22
Agreed! I ironically just fixed this for (the repository) Docker2Singularity. This I can add to the current PR. Give me a few minutes!

**Comment by vsoch** [comment] 2019-05-28 16:48
Oh good point, so you think we should have a Dockerfile ENTRYPOINT/CMD also map to a Singularity startscript? This makes sense, Docker doesn't have the equivalent (and most people would want to start the service associated with the ENTRYPOINT/CMD.

**Comment by vsoch** [comment] 2019-05-28 16:52
okay, just added to the PR to also write a `startscript`, here is an example result:

```
%runscript
cd $SRC_DIR
exec /code/salad fork "$@"
%startscript
cd $SRC_DIR
exec /code/salad fork "$@"
```

**Comment by vsoch** [comment] 2019-05-28 18:12
This was just merged in #116 https://github.com/singularityhub/singularity-cli/pull/116/files#diff-e984bd9fd64b5f8bde56908d6b24f600R215

**Comment by Flamefire** [comment] 2019-05-29 06:40
No this is not what I meant. Consider the following docker file:

```
ENTRYPOINT [ "bash" ]
CMD [ "/usr/bin/fooExe" ] 
```

The correct `%runscript` would be something like:

```
if [ $* -gt 0 ]; then exec [ "bash", "/usr/bin/fooExe" ]
else exec bash "$@"
fi
```

My proposal is to use
```
%runscript
exec bash "$@"

%startscript
exec "bash" "/usr/bin/fooExe" "$@"
```
Not sure if the latter is wise so best would probably be the `if-else` approach above to mirror docker behavior.

**Comment by vsoch** [comment] 2019-05-29 10:43
Just tested, this would work reasonably. Let's re-open and address this.

**Comment by vsoch** [comment] 2019-06-06 20:18
This I believe is also addressed with the updated recipe parser.

**Closed by vsoch** 2019-06-06 20:18 UTC

**Comment by Flamefire** [comment] 2019-06-07 07:51
Can you point me to the test which tests this? Can't find it

**Comment by vsoch** [comment] 2019-06-07 12:29
There isn't one, I had just tested it manually. I know, I know, I'm awful. :P The PR was a lot of work and it just slipped my mind.

I'm not sure how you changed the testing, but I can't get it running locally - there is a tmp_dir undefined and a missing fixture? Did you create a dependency on the CI? This is very bad :/

**Comment by Flamefire** [comment] 2019-06-07 12:33
Could you add a test then before closing this? This allows to validate that the code does what is designed here.

Do you have a recent pytest installed? I guess you meant `tmp_path` which is a fixture introduced in pytest 3.9.0

**Comment by vsoch** [comment] 2019-06-07 12:47
I just added it - and I'm also adding the missing dependencies for testing all together. There are two other deps in addition to pytest, ones that are installed with pytest --upgrade from pip. This was my mistake for not testing locally - I'll need to update the conda recipe too.

**Comment by vsoch** [comment] 2019-06-07 12:48
Just curious, you are okay with having all these additional dependencies for basic testing? It seems messy. unittest isn't as pretty, but it works standard out of the box. I am thinking it is better practice to return to that.

**Comment by Flamefire** [comment] 2019-06-07 12:51
> all these additional dependencies for basic testing?

What do you mean? `pip install pytest` is usually enough and often already on (Python) developers machine as it is widely used.

> It seems messy. unittest isn't as pretty,

So you agree unittest is messy? What do you do more often? `pip install pytest` or reading and writing test code?

Additionally pytest allows for better fixtures. Your unittest version left behind many files and running instances on failure

**Comment by vsoch** [comment] 2019-06-07 12:58
I'm torn because I like it better, but adding the dependency is something I'd not usually do (if we want to strive for optimizing reproducibility). It does seem like the consensus is for pytest regardless https://www.reddit.com/r/Python/comments/5uxh22/unittest_vs_pytest/, so I can be open minded enough to try it out :)

**Comment by vsoch** [comment] 2019-06-07 12:58
I'm torn because I like it better, but adding the dependency is something I'd not usually do (if we want to strive for optimizing reproducibility). It does seem like the consensus is for pytest regardless https://www.reddit.com/r/Python/comments/5uxh22/unittest_vs_pytest/, so I can be open minded enough to try it out :)

**Comment by Flamefire** [comment] 2019-06-07 12:59
It is a development dependency. So I don't see how this affects reproducibility
